# RuboCop configuration for Hookd Ruby client

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 25

# Allow longer blocks in RSpec tests
Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
