# Hookd Configuration Example

server:
  # Domain for the service (required)
  # All hooks will be subdomains of this domain
  domain: "hookd.domain.tld"

  dns:
    # Enable DNS server
    enabled: true
    # DNS port (requires root or CAP_NET_BIND_SERVICE for port 53)
    port: 53

  http:
    # HTTP port
    port: 80

  https:
    # Enable HTTPS
    enabled: true
    # HTTPS port
    port: 443
    # Enable Let's Encrypt automatic certificate management
    autocert: true
    # Directory to cache certificates
    cache_dir: "/var/lib/hookd/certs"

  api:
    # Authentication token for API access
    # If empty, a random token will be generated at startup
    # Can be overridden with --token CLI flag
    auth_token: ""

eviction:
  # TTL for interactions (interactions are deleted after this duration)
  # Supported formats: 30s, 5m, 1h, 24h, 48h
  interaction_ttl: "1h"

  # TTL for hooks (inactive hooks are deleted after this duration)
  # Supported formats: 30s, 5m, 1h, 24h, 48h
  hook_ttl: "24h"

  # Maximum number of interactions per hook
  # Older interactions are evicted when this limit is reached (FIFO)
  max_per_hook: 1000

  # Maximum memory usage in MB
  # Emergency eviction occurs when approaching this limit
  max_memory_mb: 1800

  # Interval for cleanup of expired interactions
  cleanup_interval: "10s"

observability:
  # Enable /metrics endpoint
  metrics_enabled: true

  # Log level: debug, info, warn, error
  log_level: "info"

  # Log format: json, text
  log_format: "json"
