name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            output: hookd-linux-amd64
          - goos: linux
            goarch: arm64
            output: hookd-linux-arm64
          - goos: darwin
            goarch: amd64
            output: hookd-darwin-amd64
          - goos: darwin
            goarch: arm64
            output: hookd-darwin-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Build binary
        working-directory: ./server
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w" -o ${{ matrix.output }} cmd/hookd/main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: server/${{ matrix.output }}
          retention-days: 30
