name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Build binaries
        working-directory: ./server
        run: |
          # Linux AMD64
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o hookd-linux-amd64 cmd/hookd/main.go

          # Linux ARM64
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o hookd-linux-arm64 cmd/hookd/main.go

          # macOS AMD64
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o hookd-darwin-amd64 cmd/hookd/main.go

          # macOS ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o hookd-darwin-arm64 cmd/hookd/main.go

      - name: Generate checksums
        working-directory: ./server
        run: |
          sha256sum hookd-* > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            server/hookd-linux-amd64
            server/hookd-linux-arm64
            server/hookd-darwin-amd64
            server/hookd-darwin-arm64
            server/checksums.txt
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
