name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-go:
    name: Test Go Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Run tests with coverage
        working-directory: ./server
        run: |
          go test -v -coverprofile=cover.out ./...

      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: server/cover.out
          strip-prefix: github.com/jomar/hookd/
          add-prefix: server/

  test-ruby:
    name: Test Ruby Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          working-directory: ./clients/ruby

      - name: Install dependencies
        working-directory: ./clients/ruby
        run: |
          gem install bundler
          bundle install

      - name: Run tests with coverage
        working-directory: ./clients/ruby
        run: |
          bundle exec rspec --format documentation

      - name: Upload coverage to Qlty
        if: always()
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: clients/ruby/coverage/.resultset.json
